### ISSUE TITLE
Automatically changing the artist image?

### ISSUE THREAD

**Issue by hans-juergen** [JasonPuglisi/descent#12]
Hi Jason, I noticed that the chosen artist image is the top voted image, but is it possible to change the artist image when the artist comes up again in a listening session or even while the track is still playing, like a slideshow? And being able to choose between blurred zoomed background image and original sized image in the settings would be nice as well, maybe also an option for album cover size.

By the way, I mentioned your latest update in related [Get Satisfaction](https://getsatisfaction.com/lastfm/topics/new-last-fm-doesnt-have-the-fullscreen-now-playing-site?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=19106756#reply_19106756), [Reddit](https://www.reddit.com/r/lastfm/comments/7dzbnm/lastfm_now_fullscreen_playing_artist_album_track/) and [Spotify](https://community.spotify.com/t5/Implemented-Ideas/Full-screen-playback-info-and-visuals-Desktop/idc-p/3209754#M25275) threads.

**Comment by JasonPuglisi** [comment]
Looking at the Last.fm API, there doesn't seem to be a way to get any of the other images apart from the top one. Might be possible to get images from Spotify but I need to look into that further.

With artist image backgrounds a possibility, I think it's worth trying out unblurred images again, but I'm not sure how awkward they'll look zoomed in. I'm hesitant to have unzoomed images since I'm not happy with letterboxing. I'll give both of these things a shot though when I have some time.

As always, thanks for the mentions :)

**Comment by hans-juergen** [comment]
Looks like the Spotify thread got deleted by a mod, strange. Anyhow, the Deezer subreddit also has a [related thread](https://www.reddit.com/r/deezer/comments/7d7h7w/full_screen_album_art_without_lyrics_possible_on/dq1eema/).

Concerning album images from Spotify the [Last.fm web scrobbler](https://github.com/david-sabata/web-scrobbler/issues?q=is:issue+is:open+sort:updated-desc) browser extension can show the album cover in a new browser tab if you click on its thumbnail preview in the Edit window by accessing their image server.

**Comment by JasonPuglisi** [comment]
Can't really do anything about alternative artist images, but I will add an option to unblur the background in #22.

**Comment by JasonPuglisi** [comment]
#22 is now closed and has an unblur option
