### ISSUE TITLE
Last.fm not returning certain artist images, and Spotify album art fallback not working

### ISSUE THREAD

**Issue by joboj** [JasonPuglisi/descent#15]
Tracks/artists with special characters in them don't find album art even when last.fm has one.

Examples:
- [What Will We Do When We Have No Money?](https://www.last.fm/music/Lankum/_/What+Will+We+Do+When+We+Have+No+Money%3F)
- [The Young'Uns](https://www.last.fm/music/The+Young%27Uns/)

**Comment by JasonPuglisi** [comment]
This doesn't seem to be related to any characters. I can reproduce the issue with both of your examples, but for different reasons.

### What Will We Do When We Have No Money?

This one successfully returns an album image, but not an artist image. I've verified that Last.fm's API is leaving the artist image blank, so maybe there isn't one voted high enough to be "approved" and returned in their API. I'm not exactly sure how they do that.

### The Young'Uns

This one doesn't return an album image. Last.fm doesn't have an album image, so it tries to fall back to Spotify. However, Spotify seems to have changed their API and no longer allows anonymous requests that we were using. API calls will need to be updated, so that'll be done in the next API change.

This one also doesn't have an artist image in Last.fm to begin with. For both cases, I could look into getting an artist image from Spotify as a fallback, similar to what we do with the album art.

**Comment by joboj** [comment]
[Sunn o))) - Che](https://www.last.fm/music/Sunn+O)))/_/che) seems to be another one.

Clicking on the now scrobbling track on my last.fm profile takes me to the above link which has album art but next to the 'from the album' link is another link to 'also featured on' which doesn't have artwork.

As an aside, did last.fm drop the option to suggest the correct meta data for a track? I thought you used to be able to suggest the corrected spelling but now all I can see is 'is this correct? - yes or no'?  Seems to be a lot of missing functionality compared to a few years ago.

**Comment by JasonPuglisi** [comment]
Fixed the Spotify API integration, and all your examples now seem to be working. Thanks for reporting!
