### ISSUE TITLE
Zoom and shading of the background image

### ISSUE THREAD

**Issue by hans-juergen** [JasonPuglisi/descent#39]
Hi Jason, I really like the unblurred artist image as background and think it still looks good. Would it be possible to choose our own zoom percentage and also the shading? I guess you zoom it to more than 200%, and most of time less might be still looking good as well showing more of the original artist image.

I use your tool on a 22" widescreen LCD monitor by Oracle/Sun with screen resolution set to 1680x1050 and 125% scaling which are the recommended Windows 10 settings. I hardly see any ugly pixeling in the background pictures, so making them brighter might work for me, too.

**Comment by JasonPuglisi** [comment]
I need to take a look at the code again, but I believe it zooms just enough to fill the screen both vertically and horizontally (whichever is longer). Zooming out would result in letterboxing, which I don't like the idea of. As for the darkness of the background, I don't really want to affect the text readability, especially since the track/artist text colors are carefully calculated/adjusted to always be readable.

I won't shoot down the ideas right away, but I also want to be wary of how many user options I add. At some point it's detrimental to the user experience, so there are trade offs to consider...

**Comment by JasonPuglisi** [comment]
Following my thoughts in the comment above, I've decided to keep things the way they are with the background. I don't want to stray too much from the current style. I hope it's still satisfactory enough though!
