### ISSUE TITLE
Integrate with Genius API to show lyrics?

### ISSUE THREAD

**Issue by mmhan** [JasonPuglisi/descent#57]
An optional feature request for those who'd like to view lyrics.

**Comment by JasonPuglisi** [comment]
I've thought about this, but I'm dissuaded by a few things. I'm not sure if Genius does live/timestamped lyrics, but even if it did (like some other paid APIs), it wouldn't work well with Last.fm. There's just no way to see where a user is in a song or if they've paused sadly.

That leaves the option of just display a whole big block of lyrics, which doesn't really fit with the design I've had in mind. I'll leave this issue open for discussion, and I might consider it if someone can propose an elegant design/solution (especially if they want to develop it too!) :)

**Comment by JasonPuglisi** [comment]
This issue has been open for a while, and unfortunately I think it would add scope and maintenance to the project that I'm not interested in taking on. In order to clean up some older issues, I'm going to close this with the `wontfix` label, but anyone is still welcome to fork the project and implement it if desired!
