### ISSUE TITLE
Add Option to enable "Idle Screensaver"

### ISSUE THREAD

**Issue by oxcid3** [JasonPuglisi/descent#58]
Assuming the concept here is for this to be displayed permanently on a wall mounted screen;
When no music is playing or scrobbling isn't working we currently get a black screen with the "There's nothing in the air" message.

Perhaps instead, the app could show facts from the specified user's Last.fm 'profile' page such as:
Top tracks
Hours of music listened to
Top albums
Top Artists etc...

With the background and album section cycling through related artwork?

**Comment by JasonPuglisi** [comment]
This issue has been open for a while, and unfortunately I think it would add scope and maintenance to the project that I'm not interested in taking on. In order to clean up some older issues, I'm going to close this with the `wontfix` label, but anyone is still welcome to fork the project and implement it if desired!
