### ISSUE TITLE
Allow alignment of image and text to center

### ISSUE THREAD

**Issue by jbrepogmailcom** [JasonPuglisi/descent#76]
On widescreen monitor 16:9 it seems to me that image is way too right. I would like to have it centered and the text below it centered as well.

Thank you, Jan

**Comment by JasonPuglisi** [comment]
This issue has been open for a while, and unfortunately I think it would add scope and maintenance to the project that I'm not interested in taking on. In order to clean up some older issues, I'm going to close this with the `wontfix` label, but anyone is still welcome to fork the project and implement it if desired!
