### ISSUE TITLE
Now Playing not showing when playing Spotify local files

### ISSUE THREAD

**Issue by Tymec** [JasonPuglisi/descent#80]
I believe it's a issue with descent.live, since last.fm scrobbles local files from Spotify fine.

**Comment by hans-juergen** [comment]
The problem is that local file scrobbling from Spotify does not provide the necessary "Scrobbling now" information in your Recent Tracks list on your Last.fm profile which is a known issue. The reason is tha tthe Spotify API does not offer this info, so it cannot be displayed, and so Descent cannot use it either.

**Comment by Tymec** [comment]
Ohhhh, i see. That's unfortunate I guess.
