### ISSUE TITLE
Give the option to set Date and Time in custom format

### ISSUE THREAD

**Issue by Dtrieb** [JasonPuglisi/descent#99]
It would be cool, if you give the option to set Date and Time in custom format.
Like in PHP.

[https://www.php.net/manual/de/function.date.php](url)

**Comment by JasonPuglisi** [comment]
This issue has been open for a while, and unfortunately I think it would add scope and maintenance to the project that I'm not interested in taking on. In order to clean up some older issues, I'm going to close this with the `wontfix` label, but anyone is still welcome to fork the project and implement it if desired!
